version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: cms
    container_name: cms-container
    restart: unless-stopped
    ports:
      - 8880:80
    environment:
      - VUE_APP_API_URL=https://api-dev-lms.digitefa.id/api
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - cms

  nginx:
    image: nginx:alpine
    container_name: cms-nginx
    restart: unless-stopped
    ports:
      - 3300:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - cms

networks:
  cms:
    driver: bridge
